version: '3.9'

services:
  # [CONTAINER][db_container] (MongoDB)
  # [INFO] accéder au shell mongo : docker exec -it db_container mongod
  # Si cela ne marche pas : mongosh --port 2717
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017 # host port : container port
    volumes:
      - ./mongoInitLocal.js:/docker-entrypoint-initdb.d/mongoInitLocal.js:ro

  # [CONTAINER][node_container] (NodeJS)
  # [INFO] the context attribute allow to the Dockerfile to have a vision in the API folder
  # without this attribute, the Dockerfile will have only a vision in the config folder
  node_api:
    container_name: node_container
    build: # build from Dockerfile in the folder
      context: .. # precise the root folder, without this, the build will be done from the current folder
      dockerfile: ./config/Dockerfile
    ports:
      - 3001:3001 # host port : container port
    environment:
      - PORT=3001
      # mongo db container name, containers does not communicate with each other using localhost
      - MONGO_DB_URL=mongodb://mongo_db:27017
      - DB_NAME=todo_db
      - TEST=true
    depends_on:
      - mongo_db

# storage manage by docker
volumes:
  mongo_db: { }
