version: '3.9'

services:
  # [CONTAINER][db_container] (MongoDB)
  # [INFO] accéder au shell mongo : docker exec -it db_container mongod
  # Si cela ne marche pas : mongosh --port 2717
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017 # host port : container port
    volumes:
      - ./mongoInitLocal.js:/docker-entrypoint-initdb.d/mongoInitLocal.js:ro

  # [CONTAINER][Bucket S3] (Picture storage)
  localstack:
    image: localstack/localstack
    #[DEBUG] interface ui web : http://localhost:8050
    #image: localstack/localstack-full:latest # Full image support WebUI
    container_name: localstack_container
  #  build:
  #    dockerfile: ./.localstack/Dockerfile
    ports:
      - '4566:4566' # port for S3
     #[DEBUG] interface ui web : http://localhost:8050
      #- '8055:8080' # port for the web interface
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/.localstack/tmp/localstack/data
      - CONTAINER_NAME=localstack_container
    volumes:
      - ./.localstack/var/lib/localstack:/var/lib/localstack
      - ./.localstack/var/run/docker.sock:/var/run/docker.sock
  #  [INFO] les paramètres AWS sont placer dans $HOME/.aws/credentials (ici: $HOME = root)
      - ./.localstack/.aws/config:/root/.aws/config
      - ./.localstack/.aws/credentials:/root/.aws/credentials


  # [CONTAINER][node_container] (NodeJS)
  # [INFO] the context attribute allow to the Dockerfile to have a vision in the API folder
  # without this attribute, the Dockerfile will have only a vision in the config folder
  node_api:
    container_name: node_container
    build: # build from Dockerfile in the folder
      context: .. # precise the root folder, without this, the build will be done from the current folder
      dockerfile: ./config/Dockerfile
    ports:
      - 3001:3001 # host port : container port
    environment:
      - PORT=3001
      # mongo db container name, containers does not communicate with each other using localhost
      - MONGO_DB_URL=mongodb://mongo_db:27017
      - DB_NAME=todo_db
      - TEST=true
      - AWS_ACCESS_KEY_ID=local_access_key
      - AWS_SECRET_KEY=local_secret_key
      - AWS_S3_SERVER=http://localstack_container:4566 #pas sur que cela
      - AWS_BUCKET_NAME=s3-bucket-test
    depends_on:
      - mongo_db

# storage manage by docker
volumes:
  mongo_db: { }